import React from 'react';
import jsPDF from 'jspdf';
import 'jspdf-autotable';

const PdfReportComponent = ({ transactions, ledgerId, startDate, endDate }) => {
  const generatePdf = () => {
    // Initialize jsPDF
    const doc = new jsPDF();

    // Add a title
    doc.setFontSize(18);
    doc.text(`Ledger Transactions Report`, 14, 22);

    // Add subtitle with ledgerId and date range
    doc.setFontSize(12);
    doc.text(`Ledger ID: ${ledgerId}`, 14, 32);
    doc.text(`Date Range: ${startDate} to ${endDate}`, 14, 40);

    // Add a table with transaction data
    doc.autoTable({
      startY: 50,
      head: [['Date', 'Name', 'Amount', 'Type']],
      body: transactions.map((transaction) => [
        new Date(transaction.date).toLocaleDateString(),
        transaction.ledgerName,
        `$${transaction.amount}`,
        transaction.transactionType,
      ]),
    });

    // Add footer
    doc.setFontSize(10);
    doc.text('Generated by LedgerTransactions', 14, doc.internal.pageSize.height - 10);

    // Save or display the PDF
    doc.save(`ledger_${ledgerId}_report.pdf`);
  };

  return (
    <button onClick={generatePdf} className="pdf-button">
      Download PDF Report
    </button>
  );
};

export default PdfReportComponent;
